// flow-typed signature: f2b15300493e576fe7029cbd4ddf5599
// flow-typed version: <<STUB>>/react-html-parser_v^2.0.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-html-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-html-parser" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-html-parser/demo/dist/app" {
  declare module.exports: any;
}

declare module "react-html-parser/demo/server" {
  declare module.exports: any;
}

declare module "react-html-parser/demo/src/js/actions" {
  declare module.exports: any;
}

declare module "react-html-parser/demo/src/js/components/App" {
  declare module.exports: any;
}

declare module "react-html-parser/demo/src/js/components/Editor" {
  declare module.exports: any;
}

declare module "react-html-parser/demo/src/js/components/Header" {
  declare module.exports: any;
}

declare module "react-html-parser/demo/src/js/components/Html" {
  declare module.exports: any;
}

declare module "react-html-parser/demo/src/js/containers/Content" {
  declare module.exports: any;
}

declare module "react-html-parser/demo/src/js/containers/Editor" {
  declare module.exports: any;
}

declare module "react-html-parser/demo/src/js/containers/Html" {
  declare module.exports: any;
}

declare module "react-html-parser/demo/src/js/data/entities/index" {
  declare module.exports: any;
}

declare module "react-html-parser/demo/src/js/data/entities/options" {
  declare module.exports: any;
}

declare module "react-html-parser/demo/src/js/data/index" {
  declare module.exports: any;
}

declare module "react-html-parser/demo/src/js/data/simple/index" {
  declare module.exports: any;
}

declare module "react-html-parser/demo/src/js/data/simple/options" {
  declare module.exports: any;
}

declare module "react-html-parser/demo/src/js/data/transform/index" {
  declare module.exports: any;
}

declare module "react-html-parser/demo/src/js/data/transform/options" {
  declare module.exports: any;
}

declare module "react-html-parser/demo/src/js/index" {
  declare module.exports: any;
}

declare module "react-html-parser/demo/src/js/reducers" {
  declare module.exports: any;
}

declare module "react-html-parser/dist/react-html-parser" {
  declare module.exports: any;
}

declare module "react-html-parser/dist/react-html-parser.min" {
  declare module.exports: any;
}

declare module "react-html-parser/lib/convertNodeToElement" {
  declare module.exports: any;
}

declare module "react-html-parser/lib/dom/attributes/BooleanAttributes" {
  declare module.exports: any;
}

declare module "react-html-parser/lib/dom/attributes/ReactAttributes" {
  declare module.exports: any;
}

declare module "react-html-parser/lib/dom/elements/VoidElements" {
  declare module.exports: any;
}

declare module "react-html-parser/lib/elementTypes/index" {
  declare module.exports: any;
}

declare module "react-html-parser/lib/elementTypes/StyleElementType" {
  declare module.exports: any;
}

declare module "react-html-parser/lib/elementTypes/TagElementType" {
  declare module.exports: any;
}

declare module "react-html-parser/lib/elementTypes/TextElementType" {
  declare module.exports: any;
}

declare module "react-html-parser/lib/elementTypes/UnsupportedElementType" {
  declare module.exports: any;
}

declare module "react-html-parser/lib/HtmlParser" {
  declare module.exports: any;
}

declare module "react-html-parser/lib/index" {
  declare module.exports: any;
}

declare module "react-html-parser/lib/processNodes" {
  declare module.exports: any;
}

declare module "react-html-parser/lib/utils/generatePropsFromAttributes" {
  declare module.exports: any;
}

declare module "react-html-parser/lib/utils/htmlAttributesToReact" {
  declare module.exports: any;
}

declare module "react-html-parser/lib/utils/inlineStyleToObject" {
  declare module.exports: any;
}

declare module "react-html-parser/lib/utils/isEmptyTextNode" {
  declare module.exports: any;
}

declare module "react-html-parser/lib/utils/isValidTagOrAttributeName" {
  declare module.exports: any;
}

declare module "react-html-parser/scripts/attributes-diff" {
  declare module.exports: any;
}

declare module "react-html-parser/src/convertNodeToElement" {
  declare module.exports: any;
}

declare module "react-html-parser/src/dom/attributes/BooleanAttributes" {
  declare module.exports: any;
}

declare module "react-html-parser/src/dom/attributes/ReactAttributes" {
  declare module.exports: any;
}

declare module "react-html-parser/src/dom/elements/VoidElements" {
  declare module.exports: any;
}

declare module "react-html-parser/src/elementTypes/index" {
  declare module.exports: any;
}

declare module "react-html-parser/src/elementTypes/StyleElementType" {
  declare module.exports: any;
}

declare module "react-html-parser/src/elementTypes/TagElementType" {
  declare module.exports: any;
}

declare module "react-html-parser/src/elementTypes/TextElementType" {
  declare module.exports: any;
}

declare module "react-html-parser/src/elementTypes/UnsupportedElementType" {
  declare module.exports: any;
}

declare module "react-html-parser/src/HtmlParser" {
  declare module.exports: any;
}

declare module "react-html-parser/src/index" {
  declare module.exports: any;
}

declare module "react-html-parser/src/processNodes" {
  declare module.exports: any;
}

declare module "react-html-parser/src/utils/generatePropsFromAttributes" {
  declare module.exports: any;
}

declare module "react-html-parser/src/utils/htmlAttributesToReact" {
  declare module.exports: any;
}

declare module "react-html-parser/src/utils/inlineStyleToObject" {
  declare module.exports: any;
}

declare module "react-html-parser/src/utils/isEmptyTextNode" {
  declare module.exports: any;
}

declare module "react-html-parser/src/utils/isValidTagOrAttributeName" {
  declare module.exports: any;
}

// Filename aliases
declare module "react-html-parser/demo/dist/app.js" {
  declare module.exports: $Exports<"react-html-parser/demo/dist/app">;
}
declare module "react-html-parser/demo/server.js" {
  declare module.exports: $Exports<"react-html-parser/demo/server">;
}
declare module "react-html-parser/demo/src/js/actions.js" {
  declare module.exports: $Exports<"react-html-parser/demo/src/js/actions">;
}
declare module "react-html-parser/demo/src/js/components/App.js" {
  declare module.exports: $Exports<
    "react-html-parser/demo/src/js/components/App"
  >;
}
declare module "react-html-parser/demo/src/js/components/Editor.js" {
  declare module.exports: $Exports<
    "react-html-parser/demo/src/js/components/Editor"
  >;
}
declare module "react-html-parser/demo/src/js/components/Header.js" {
  declare module.exports: $Exports<
    "react-html-parser/demo/src/js/components/Header"
  >;
}
declare module "react-html-parser/demo/src/js/components/Html.js" {
  declare module.exports: $Exports<
    "react-html-parser/demo/src/js/components/Html"
  >;
}
declare module "react-html-parser/demo/src/js/containers/Content.js" {
  declare module.exports: $Exports<
    "react-html-parser/demo/src/js/containers/Content"
  >;
}
declare module "react-html-parser/demo/src/js/containers/Editor.js" {
  declare module.exports: $Exports<
    "react-html-parser/demo/src/js/containers/Editor"
  >;
}
declare module "react-html-parser/demo/src/js/containers/Html.js" {
  declare module.exports: $Exports<
    "react-html-parser/demo/src/js/containers/Html"
  >;
}
declare module "react-html-parser/demo/src/js/data/entities/index.js" {
  declare module.exports: $Exports<
    "react-html-parser/demo/src/js/data/entities/index"
  >;
}
declare module "react-html-parser/demo/src/js/data/entities/options.js" {
  declare module.exports: $Exports<
    "react-html-parser/demo/src/js/data/entities/options"
  >;
}
declare module "react-html-parser/demo/src/js/data/index.js" {
  declare module.exports: $Exports<"react-html-parser/demo/src/js/data/index">;
}
declare module "react-html-parser/demo/src/js/data/simple/index.js" {
  declare module.exports: $Exports<
    "react-html-parser/demo/src/js/data/simple/index"
  >;
}
declare module "react-html-parser/demo/src/js/data/simple/options.js" {
  declare module.exports: $Exports<
    "react-html-parser/demo/src/js/data/simple/options"
  >;
}
declare module "react-html-parser/demo/src/js/data/transform/index.js" {
  declare module.exports: $Exports<
    "react-html-parser/demo/src/js/data/transform/index"
  >;
}
declare module "react-html-parser/demo/src/js/data/transform/options.js" {
  declare module.exports: $Exports<
    "react-html-parser/demo/src/js/data/transform/options"
  >;
}
declare module "react-html-parser/demo/src/js/index.js" {
  declare module.exports: $Exports<"react-html-parser/demo/src/js/index">;
}
declare module "react-html-parser/demo/src/js/reducers.js" {
  declare module.exports: $Exports<"react-html-parser/demo/src/js/reducers">;
}
declare module "react-html-parser/dist/react-html-parser.js" {
  declare module.exports: $Exports<"react-html-parser/dist/react-html-parser">;
}
declare module "react-html-parser/dist/react-html-parser.min.js" {
  declare module.exports: $Exports<
    "react-html-parser/dist/react-html-parser.min"
  >;
}
declare module "react-html-parser/lib/convertNodeToElement.js" {
  declare module.exports: $Exports<
    "react-html-parser/lib/convertNodeToElement"
  >;
}
declare module "react-html-parser/lib/dom/attributes/BooleanAttributes.js" {
  declare module.exports: $Exports<
    "react-html-parser/lib/dom/attributes/BooleanAttributes"
  >;
}
declare module "react-html-parser/lib/dom/attributes/ReactAttributes.js" {
  declare module.exports: $Exports<
    "react-html-parser/lib/dom/attributes/ReactAttributes"
  >;
}
declare module "react-html-parser/lib/dom/elements/VoidElements.js" {
  declare module.exports: $Exports<
    "react-html-parser/lib/dom/elements/VoidElements"
  >;
}
declare module "react-html-parser/lib/elementTypes/index.js" {
  declare module.exports: $Exports<"react-html-parser/lib/elementTypes/index">;
}
declare module "react-html-parser/lib/elementTypes/StyleElementType.js" {
  declare module.exports: $Exports<
    "react-html-parser/lib/elementTypes/StyleElementType"
  >;
}
declare module "react-html-parser/lib/elementTypes/TagElementType.js" {
  declare module.exports: $Exports<
    "react-html-parser/lib/elementTypes/TagElementType"
  >;
}
declare module "react-html-parser/lib/elementTypes/TextElementType.js" {
  declare module.exports: $Exports<
    "react-html-parser/lib/elementTypes/TextElementType"
  >;
}
declare module "react-html-parser/lib/elementTypes/UnsupportedElementType.js" {
  declare module.exports: $Exports<
    "react-html-parser/lib/elementTypes/UnsupportedElementType"
  >;
}
declare module "react-html-parser/lib/HtmlParser.js" {
  declare module.exports: $Exports<"react-html-parser/lib/HtmlParser">;
}
declare module "react-html-parser/lib/index.js" {
  declare module.exports: $Exports<"react-html-parser/lib/index">;
}
declare module "react-html-parser/lib/processNodes.js" {
  declare module.exports: $Exports<"react-html-parser/lib/processNodes">;
}
declare module "react-html-parser/lib/utils/generatePropsFromAttributes.js" {
  declare module.exports: $Exports<
    "react-html-parser/lib/utils/generatePropsFromAttributes"
  >;
}
declare module "react-html-parser/lib/utils/htmlAttributesToReact.js" {
  declare module.exports: $Exports<
    "react-html-parser/lib/utils/htmlAttributesToReact"
  >;
}
declare module "react-html-parser/lib/utils/inlineStyleToObject.js" {
  declare module.exports: $Exports<
    "react-html-parser/lib/utils/inlineStyleToObject"
  >;
}
declare module "react-html-parser/lib/utils/isEmptyTextNode.js" {
  declare module.exports: $Exports<
    "react-html-parser/lib/utils/isEmptyTextNode"
  >;
}
declare module "react-html-parser/lib/utils/isValidTagOrAttributeName.js" {
  declare module.exports: $Exports<
    "react-html-parser/lib/utils/isValidTagOrAttributeName"
  >;
}
declare module "react-html-parser/scripts/attributes-diff.js" {
  declare module.exports: $Exports<"react-html-parser/scripts/attributes-diff">;
}
declare module "react-html-parser/src/convertNodeToElement.js" {
  declare module.exports: $Exports<
    "react-html-parser/src/convertNodeToElement"
  >;
}
declare module "react-html-parser/src/dom/attributes/BooleanAttributes.js" {
  declare module.exports: $Exports<
    "react-html-parser/src/dom/attributes/BooleanAttributes"
  >;
}
declare module "react-html-parser/src/dom/attributes/ReactAttributes.js" {
  declare module.exports: $Exports<
    "react-html-parser/src/dom/attributes/ReactAttributes"
  >;
}
declare module "react-html-parser/src/dom/elements/VoidElements.js" {
  declare module.exports: $Exports<
    "react-html-parser/src/dom/elements/VoidElements"
  >;
}
declare module "react-html-parser/src/elementTypes/index.js" {
  declare module.exports: $Exports<"react-html-parser/src/elementTypes/index">;
}
declare module "react-html-parser/src/elementTypes/StyleElementType.js" {
  declare module.exports: $Exports<
    "react-html-parser/src/elementTypes/StyleElementType"
  >;
}
declare module "react-html-parser/src/elementTypes/TagElementType.js" {
  declare module.exports: $Exports<
    "react-html-parser/src/elementTypes/TagElementType"
  >;
}
declare module "react-html-parser/src/elementTypes/TextElementType.js" {
  declare module.exports: $Exports<
    "react-html-parser/src/elementTypes/TextElementType"
  >;
}
declare module "react-html-parser/src/elementTypes/UnsupportedElementType.js" {
  declare module.exports: $Exports<
    "react-html-parser/src/elementTypes/UnsupportedElementType"
  >;
}
declare module "react-html-parser/src/HtmlParser.js" {
  declare module.exports: $Exports<"react-html-parser/src/HtmlParser">;
}
declare module "react-html-parser/src/index.js" {
  declare module.exports: $Exports<"react-html-parser/src/index">;
}
declare module "react-html-parser/src/processNodes.js" {
  declare module.exports: $Exports<"react-html-parser/src/processNodes">;
}
declare module "react-html-parser/src/utils/generatePropsFromAttributes.js" {
  declare module.exports: $Exports<
    "react-html-parser/src/utils/generatePropsFromAttributes"
  >;
}
declare module "react-html-parser/src/utils/htmlAttributesToReact.js" {
  declare module.exports: $Exports<
    "react-html-parser/src/utils/htmlAttributesToReact"
  >;
}
declare module "react-html-parser/src/utils/inlineStyleToObject.js" {
  declare module.exports: $Exports<
    "react-html-parser/src/utils/inlineStyleToObject"
  >;
}
declare module "react-html-parser/src/utils/isEmptyTextNode.js" {
  declare module.exports: $Exports<
    "react-html-parser/src/utils/isEmptyTextNode"
  >;
}
declare module "react-html-parser/src/utils/isValidTagOrAttributeName.js" {
  declare module.exports: $Exports<
    "react-html-parser/src/utils/isValidTagOrAttributeName"
  >;
}
