// flow-typed signature: be8fbde382469aa8fbc0a917b19627cf
// flow-typed version: <<STUB>>/webpack-obfuscator_v^0.18.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-obfuscator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "webpack-obfuscator" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "webpack-obfuscator/test/config/webpack.config" {
  declare module.exports: any;
}

declare module "webpack-obfuscator/test/input/index-excluded" {
  declare module.exports: any;
}

declare module "webpack-obfuscator/test/input/index" {
  declare module.exports: any;
}

// Filename aliases
declare module "webpack-obfuscator/index" {
  declare module.exports: $Exports<"webpack-obfuscator">;
}
declare module "webpack-obfuscator/index.js" {
  declare module.exports: $Exports<"webpack-obfuscator">;
}
declare module "webpack-obfuscator/test/config/webpack.config.js" {
  declare module.exports: $Exports<
    "webpack-obfuscator/test/config/webpack.config"
  >;
}
declare module "webpack-obfuscator/test/input/index-excluded.js" {
  declare module.exports: $Exports<
    "webpack-obfuscator/test/input/index-excluded"
  >;
}
declare module "webpack-obfuscator/test/input/index.js" {
  declare module.exports: $Exports<"webpack-obfuscator/test/input/index">;
}
